idf_component_register(
    SRCS
        "main.c"
        "qma6100p.c"
        "adc_button.c"
        "wifi_app.c"
        "http_server.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        driver
        esp_wifi
        nvs_flash
        esp_http_server
        esp_timer
        esp_adc
        esp_psram
        json
)